# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet/CMakeFiles /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cpp_SDL_Program

# Build rule for target.
Cpp_SDL_Program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Cpp_SDL_Program
.PHONY : Cpp_SDL_Program

# fast build rule for target.
Cpp_SDL_Program/fast:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/build
.PHONY : Cpp_SDL_Program/fast

src/SDL2_gfxPrimitives.o: src/SDL2_gfxPrimitives.c.o

.PHONY : src/SDL2_gfxPrimitives.o

# target to build an object file
src/SDL2_gfxPrimitives.c.o:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/SDL2_gfxPrimitives.c.o
.PHONY : src/SDL2_gfxPrimitives.c.o

src/SDL2_gfxPrimitives.i: src/SDL2_gfxPrimitives.c.i

.PHONY : src/SDL2_gfxPrimitives.i

# target to preprocess a source file
src/SDL2_gfxPrimitives.c.i:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/SDL2_gfxPrimitives.c.i
.PHONY : src/SDL2_gfxPrimitives.c.i

src/SDL2_gfxPrimitives.s: src/SDL2_gfxPrimitives.c.s

.PHONY : src/SDL2_gfxPrimitives.s

# target to generate assembly for a file
src/SDL2_gfxPrimitives.c.s:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/SDL2_gfxPrimitives.c.s
.PHONY : src/SDL2_gfxPrimitives.c.s

src/application_ui.o: src/application_ui.cpp.o

.PHONY : src/application_ui.o

# target to build an object file
src/application_ui.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/application_ui.cpp.o
.PHONY : src/application_ui.cpp.o

src/application_ui.i: src/application_ui.cpp.i

.PHONY : src/application_ui.i

# target to preprocess a source file
src/application_ui.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/application_ui.cpp.i
.PHONY : src/application_ui.cpp.i

src/application_ui.s: src/application_ui.cpp.s

.PHONY : src/application_ui.s

# target to generate assembly for a file
src/application_ui.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/application_ui.cpp.s
.PHONY : src/application_ui.cpp.s

src/fonctions.o: src/fonctions.cpp.o

.PHONY : src/fonctions.o

# target to build an object file
src/fonctions.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/fonctions.cpp.o
.PHONY : src/fonctions.cpp.o

src/fonctions.i: src/fonctions.cpp.i

.PHONY : src/fonctions.i

# target to preprocess a source file
src/fonctions.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/fonctions.cpp.i
.PHONY : src/fonctions.cpp.i

src/fonctions.s: src/fonctions.cpp.s

.PHONY : src/fonctions.s

# target to generate assembly for a file
src/fonctions.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/fonctions.cpp.s
.PHONY : src/fonctions.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Cpp_SDL_Program.dir/build.make CMakeFiles/Cpp_SDL_Program.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Cpp_SDL_Program"
	@echo "... src/SDL2_gfxPrimitives.o"
	@echo "... src/SDL2_gfxPrimitives.i"
	@echo "... src/SDL2_gfxPrimitives.s"
	@echo "... src/application_ui.o"
	@echo "... src/application_ui.i"
	@echo "... src/application_ui.s"
	@echo "... src/fonctions.o"
	@echo "... src/fonctions.i"
	@echo "... src/fonctions.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /mnt/d/temp/Scolaire/IMAC-ESIPE/Algo_prog/projet/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

